# The URL the site will be built for
base_url = "/"

# Used in RSS by default
title = "My blog!"
description = "placeholder description text for your blog!"

# The default language, used in RSS
# TODO: I would love to support more languages and make this easy to handle
# with other facets of the theme.
default_language = "en"

# Whether to generate a RSS feed automatically
generate_feed = true
feed_filename = "rss.xml"

# Theme name to use.
# NOTE: should not need to mess with this if you are using zerm directly, i.e. cloning the
# repository at root and not using as directed by the Zola docs via themes/ directory.
# theme = ""

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Syntax highlighting theme. See:
# https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
# for more information and themes built into Zola.
highlight_theme = "axar" # Other dark themes that work: "1337", "agola-dark",
                         # "visual-studio-dark"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Built in taxonomies of zerm. 
taxonomies = [
           {name = "tags"},
           {name = "categories"},
]

[extra]
# Put all your custom variables here
#
# Many configurations are taken directly from Terminal's config.toml
# ---------------------------------------------------------

# Author name to be added to posts, if enabled.
author = "you!"

# Show author's name in blog post meta data.
show_author = false

# Show categories a blog post is marked with in its meta data.
show_categories = true

# Show tags a blog post is marked with in its meta data.
show_tags = true

# Show cover images in lists
show_covers_in_lists = true

# Theme color. You can have any color you want, so long as it's...
# ["orange", "blue", "red", "green", "pink"]
theme_color = "orange"

# Custom css to style over the defaults. This is useful when you only have a
# few small tweaks to make rather than a major rehaul to the theme.
# It would be best to make this a proper .sass or .scss file in sass/ rather
# than placing in static/
# custom_css = "custom.css"

# Enable math inside articles with `math=true` property
enable_katex = true

# How many menu items to show on desktop. if you set this to 0, only submenu
# button will be visible.
show_menu_items = 2

# set theme to full screen width.
full_width = false

# center theme with default width.
center = false

# set a custom favicon. Must be placed in root of static/ directory...
# favicon = ""

# Set a custom preview image for your website when posted as a link.
# Must be placed in root of static/ directory...
# og_preview_img = ""

# Copyright notice if desired. Defaults to 
# copyright = "copyright notice here"

# What is displayed in the top left corner of the website. Default is zerm.
logo_text = "zerm"

# Link in logo. Default returns you to $BASE_URL.
logo_home_link = "/"

# Menu items to display. You define a url and the name of the menu item.
# NOTE: `$BASE_URL/` must be included in the url name.
main_menu = [
              {url="/about/", name="about"},
              {url="/contact/", name="contact"},
]

# Displayed as title of drop-down menu when size of main_menu > show_menu_items.
menu_more = "show more"

# Displayed after teaser text for a blog post.
read_more = "read more"

# Displayed on the separator of donation section, if you want this section
support_us = "support us"

# Displayed on the separator of follow me section, if you want this section
follow_me = "follow me"

# Displayed before input group for copying to clipboard the present URL
url_to_clipboard = "Copy this page URL to your clipboard"

# not currently used from previous theme, but leaving here for now in case I
# feel like adding it.
read_other_posts = "read other posts"

# Enable/Disable DDG search integration
ddg_search = true

# Set a custom website. Otherwise DDG will search on the `base_url`
# ddg_website = "custom.website.com"

# Set a language for your research
# ddg_lang="en-en"

# DDG colors
# ddg_color_background
# ddg_color_header
# ddg_color_urls
# ddg_color_text
# ddg_color_links
# ddg_color_visited

# ddg_theme

# Text size 
#   n for Large (default)
#   l for Larger
#   t for Largest
#   m for Medium
#   s for Small 

ddg_text_size = "l"

# Add a "Go" button on side
# ddg_button

# Dark/Light mode switcher
theme_switcher = true

# Twitter support
twitter_site="@username" # for the website used in the card footer
twitter_user="@username" # for the content creator/author (you can overwrite it on page metadata)
